version: '{branch}-{build}'
image: Visual Studio 2019

install:
- ps: |-
    Install-Product node 12.18.3 x64

cache:
- source/WebApp/node_modules -> source/WebApp/package.json

build_script:
- SET NODE_ENV=ci
- cmd: sl ci

artifacts:
- path: ./Server.zip
  name: Server.zip
- path: ./Server.NetFramework.zip
  name: Server.NetFramework.zip
- path: ./WebApp.zip
  name: WebApp.zip

deploy:

- provider: AzureAppServiceZipDeploy
  website: sharplab-edge
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: WebApp.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sl-a-edge-core-x64
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sl-a-edge-core-x64-profiled
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sl-a-edge-netfx
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.NetFramework.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sl-a-edge-netfx-x64
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.NetFramework.zip
  on:
    branch: edge

- provider: AzureAppServiceZipDeploy
  website: sharplab
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: WebApp.zip
  on:
    branch: main

- provider: AzureAppServiceZipDeploy
  website: sl-a-core-x64
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.zip
  on:
    branch: main

- provider: AzureAppServiceZipDeploy
  website: sl-a-core-x64-profiled
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.zip
  on:
    branch: main

- provider: AzureAppServiceZipDeploy
  website: sl-a-x64
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.NetFramework.zip
  on:
    branch: main

- provider: AzureAppServiceZipDeploy
  website: sl-a-netfx
  username: ashmind
  password:
    secure: FUzpPhO20JDsbK33tI4pWUiu2GJzkMRGPbFpXjXCOHMHAs39F0tPqb6v4qQzGTYix/mA2Qhee4wFcX4H8zSPeA==
  artifact: Server.NetFramework.zip
  on:
    branch: main